// A map to hold active Server-Sent Event (SSE) response objects.
// Key: connectionId (UUID generated by frontend), Value: Express Response object
const clients = new Map();

export const sseService = {
    addClient: (connectionId, res) => {
        // Standard headers for SSE
        res.writeHead(200, {
            'Content-Type': 'text/event-stream',
            'Cache-Control': 'no-cache',
            'Connection': 'keep-alive',
            // Allow CORS if needed, though global middleware usually handles this
        });

        // Tell the frontend we are ready
        res.write(`event: connected\ndata: {"status": "SSE stream established"}\n\n`);

        clients.set(connectionId, res);

        // Keep-alive heartbeat (prevents proxy/browser timeouts)
        const heartbeat = setInterval(() => {
            if (clients.has(connectionId)) {
                res.write(': heartbeat\n\n'); // SSE comment, ignored by frontend onmessage
            } else {
                clearInterval(heartbeat);
            }
        }, 15000); // 15 seconds

        // Cleanup on disconnect
        req.on('close', () => {
            clearInterval(heartbeat);
            clients.delete(connectionId);
        });
    },

    removeClient: (connectionId) => {
        const client = clients.get(connectionId);
        if (client) {
            client.end();
            clients.delete(connectionId);
        }
    },

    // Push an event to a specific client
    sendEvent: (connectionId, eventType, payload) => {
        const client = clients.get(connectionId);
        if (client) {
            // SSE Format: 
            // event: type
            // data: stringified_json
            // \n\n
            client.write(`event: ${eventType}\ndata: ${JSON.stringify(payload)}\n\n`);
        }
    }
};